project_name: glab

before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./cmd/glab
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X glab.version={{.Version}} -X glab.commit={{.Commit}} -X glab.build={{time "01/02/2006"}}
  - <<: &build_defaults
      binary: bin/glab
      main: ./cmd/glab
    id: macos
    goos: [darwin]
    goarch: [amd64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
      linux: Linux
    format: tar.gz

  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip

scoop:
  url_template: "http://github.com/profclems/glab/releases/{{ .Tag }}/{{ .ArtifactName }}"
  # Repository to push the app manifest to.
  bucket:
    owner: profclems
    name: scoop-glab
  commit_author:
    name: Clement Sam
    email: clementsam75@gmail.com
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://github.com/profclems/glab"
  description: "An open source gitlab cli tool"
  license: MIT
  persist:
    - ".glab-cli"
    - ".env"

brews:
  - name: glab
    ids:
      - nix
    description: "An open source gitlab cli tool"
    commit_author:
      name: Clement Sam
      email: clementsam75@gmail.com
    folder: Formula
    goarm: 6
    tap:
      owner: profclems
      name: homebrew-tap
    url_template: "http://github.com/profclems/glab/releases/{{ .Tag }}/{{ .ArtifactName }}"
    # Packages your package depends on.
    homepage: "https://github.com/profclems/glab"
    dependencies:
      - name: git
    test: |
      system "#{bin}/glab --version"
nfpms:
  -
    id: foo
    package_name: glab
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    # Build IDs for the builds you want to create NFPM packages for.
    # Defaults to all builds.

    replacements:
      amd64: x86_64
      386: i386
      darwin: macOS
      linux: Linux
    vendor: Clement Sam
    homepage: https://github.com/profclems/glab
    maintainer: Clement Sam <clementsam75@gmail.com>
    description: An open source gitlab cli tool
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - git
    # Override default /usr/local/bin destination for binaries
    bindir: /usr/local/bin
    epoch: 1
    release: 1
    meta: true
    empty_folders:
      - ~/.glab-cli/config

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
