project_name: glab

release:
  prerelease: auto
  
before:
  hooks:
    - go mod tidy
    
builds:
  - <<: &build_defaults
      main: ./cmd/glab
      binary: bin/glab
      env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X main.version={{.Version}} -X main.build={{time "2006-01-02"}}
    id: macos
    goos: [darwin]
    goarch: [amd64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      wrap_in_directory: false
    format: tar.gz
    replacements: 
      darwin: macOS
      linux: Linux
      <<: &arch_replacemens
        386: i386
        amd64: x86_64

  - id: windows
    builds: [windows]
    <<: *archive_defaults
    format: zip
    replacements: 
      windows: Windows
      <<: *arch_replacemens

scoop:
  url_template: "http://github.com/profclems/glab/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  # Repository to push the app manifest to.
  bucket:
    owner: profclems
    name: scoop-glab
  commit_author:
    name: Clement Sam
    email: clementsam75@gmail.com
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://github.com/profclems/glab"
  description: "An open source gitlab cli tool"
  license: MIT
  persist:
    - ".glab-cli"
    - ".env"

brews:
  - name: glab
    ids:
      - nix
    description: "An open source GitLab CLI tool"
    commit_author:
      name: Clement Sam
      email: clementsam75@gmail.com
    folder: Formula
    goarm: 6
    tap:
      owner: profclems
      name: homebrew-tap
    url_template: "http://github.com/profclems/glab/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    # Packages your package depends on.
    homepage: "https://github.com/profclems/glab"
    dependencies:
      - name: git
    install: bin.install "bin/glab"
    test: |
      system "#{bin}/glab version"
      
nfpms:
  -
    id: foo
    package_name: glab
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    # Build IDs for the builds you want to create NFPM packages for.
    # Defaults to all builds.

    replacements:
      amd64: x86_64
      386: i386
      darwin: macOS
      linux: Linux
    vendor: Clement Sam
    homepage: https://github.com/profclems/glab
    maintainer: Clement Sam <clementsam75@gmail.com>
    description: An open source gitlab cli tool
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - git
    # Override default /usr/local/bin destination for binaries
    bindir: /usr/local/bin

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
      - '^chore'
      - '^Update README.md'
