language: go
os:
  - linux
go:
  - 1.15.x

cache:
  directories:
  - "$HOME/.cache/go-build"
  - "$HOME/gopath/pkg/mod"
addons:
  ssh_known_hosts:
  - gitlab.com
before_install:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - go get -t -v ./...
  - echo -e "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCc54ULcDSmuQBMaM52dqxNMETAlwn01AF79vJb6Nw3SzkNKEMY1pBttM1U8wz7dHpVteAQGCU2AH+T2UhswZWPIzcMfVwB+1RgcIkHW184V5FX1xxqo4Xx6CC6LTSq3md/EmXfQR7gAwaKQHy6txxYpEprlhw+EWICgD5znUMprRRbcsb2FoAdsodMWSl5aRIyC1rA06SKKwqN09o4mgNhv49McyzDnUCGmSTc0oQpygPadDRqW46iCkMdiJa1fuP9pSGkAuTaQayILbDenAM3cV7LqsIm7tOXLPW5fQm9FB91ftRLXxk1Mp6lMYqNc5eGoR4ATzHn7M/VHbBaqVlp profclems@ProfClems" > ~/.ssh/id_rsa.pub
  - echo -e "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn\nNhAAAAAwEAAQAAAQEAnOeFC3A0prkATGjOdnasTTBEwJcJ9NQBe/byW+jcN0s5DShDGNaQ\nbbTNVPMM+3R6VbXgEBglNgB/k9lIbMGVjyM3DH1cAftUYHCJB1tfOFeRV9ccaqOF8eggui\n00qt5nfxJl30Ee4AMGikB8urccWKRKa5YcPhFiAoA+c51DKa0UW3LG9haAHbKHTFkpeWkS\nMgtawNOkiisKjdPaOJoDYb+PTHMsw51Ahpkk3NKEKcoD2nQ0aluOogpDHYiWtX7j/aUhpA\nLk2kGsiC2w3pwDN3Fey6rCJu7Tlyz1uX0JvRQfdX7US18ZNTKepTGKjXOXhqEeAE8x5+zP\n1R2wWqlZaQAAA8j2Yikl9mIpJQAAAAdzc2gtcnNhAAABAQCc54ULcDSmuQBMaM52dqxNME\nTAlwn01AF79vJb6Nw3SzkNKEMY1pBttM1U8wz7dHpVteAQGCU2AH+T2UhswZWPIzcMfVwB\n+1RgcIkHW184V5FX1xxqo4Xx6CC6LTSq3md/EmXfQR7gAwaKQHy6txxYpEprlhw+EWICgD\n5znUMprRRbcsb2FoAdsodMWSl5aRIyC1rA06SKKwqN09o4mgNhv49McyzDnUCGmSTc0oQp\nygPadDRqW46iCkMdiJa1fuP9pSGkAuTaQayILbDenAM3cV7LqsIm7tOXLPW5fQm9FB91ft\nRLXxk1Mp6lMYqNc5eGoR4ATzHn7M/VHbBaqVlpAAAAAwEAAQAAAQAJvxv1nO+4V4+cL3p7\nw11qog/zQq6cpbq935YofWuIh8Swe4rHdTSdi/ihSUPKLu8WeejENyvAkgFaxsmH7/KBZL\nebsAHSIbGZGAR7D4L3tgDSSwt52FSOtVOrHPnDj3MwYo0vdBUd5zI1zlGxK4S4QORakIWK\nmXvUGfFHL0KnyP6uH3Z/j8hQaAE8TIVrGM6PyLes3NWFTlXIakrV8jiJc5bxVnhzDcIKdf\n9JUYGO3DUCQI+pdkCfMNptbBuGwqHjruruGYMfh+mx7FrnpjbJ3y2TG01pcXBeCRIJNm2/\n4htjlAxdz2Zxa8JL437s56Jf4ZtDOYt367dhTMRBleoxAAAAgDo0de+4nNSVb/H3aGo5Y0\nLg/q/npYUNVSvZ9R0GfRY0qDbNCaKeqbyJDkReRn5R/KKT9+Gx0/zqXGNi1ubnGtxqCCmC\nYHDys0PSw6yAEDZ3JOeYWEIO7ntH0DKdErcEUj+FqatdIpoZZO48XZDSXzO1+B1n2y+AML\nfyMggdFXIBAAAAgQDMnIFss9kLpnqC5QOAiDO+jsnHwNHENBgQKE9/jM6gagaK3T4TDkJl\nPszXRDE11LSBCxahL5rxwWDog1vG67tnbfznjhGm8Fd+mEs6omuQ5pA0o6Qx40xtkfn3vi\nj4NLkpo5rYg0DTtciDgGeibtt1oT1EhKZ59ystGdFgSGWxtQAAAIEAxE+xPCLHzqEUUlxI\nSJC6+e2hUT/9s64OwmH9pCrQ8+96G9TtbR9NFD1LSArnLXvl6ooYODw0QDjLdgCUQj63r7\nqOV9QjWKL6xD1atN37WFbrIpem8pFOJWinYrQtddANSBd5tp5QsDkI58ovqhdDuYoVfL1y\nmEfWvucOVlZraWUAAAATcHJvZmNsZW1zQFByb2ZDbGVtcw==\n-----END OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa*
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa

script:
  - make tests

after_success:
  - |
    for r in $(ag -Q 'log.Fatal' | awk -F: '{ print "github.com/profclems/glab/" $1 ":" $2-1 "\\.[0-9][0-9]\\?," $2+1 }' | sed 's|/|\\/|g')
      do sed -i "/$r/d" coverage.txt
    done
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
env:
  global:
    secure: Yo4OYHzldo3X3aqCbFdocz3jQ4EsUG44gyrBkHKd5ggQFTedug70zLyqG6SZORDAql6CEaH/IMzRi45NQhWqot5Ezv09/7J9BvELCk2HOgM111IC90BZHQW93OOr2WHwWvzFQDK1kXSJIlGubyD1GBQOFMSwV8hZQams/gGb7JUUwCBmYbX+rd0aMxtD6GGn/6WzlKO1mfFf/UPxvWMsiKx0TTti25q7gZmPIdS3yUFtlvuwqDUzRnzwNKYuEHHnClvWkNBg3I58a+nqrjGIuogh5NOIDSIFjdhtMy8L75N12WNXcQf36SA9BFz8xpdbgsK0I/cMerc03UNCA9CDxYStPxAmPwXnYsfdSRfcQv82U+OcBr56DPU0QPiDYv4o++kAt93RBcOmiVvDNZ28agJ+7Ajd8Yu5HLd12A+CKfuBqugc/8J8a0YpSJGchwb3xvtHWws06FfRQL3oSpslmlUqjRDTx/wLqJ1DETsSsWfruVYnnbNu+HUEMTKAjyMIV1hcLaH9vO3HUWWL6iUbusZxa1OkfiVVK3HyZF4aOLaPWTN5AB1ADaZ8ypequ9+2/xXi+YW6Ay0FyGtkIZNq28lbdbb7BcgtPUZaKFiFuWOw9qF8zJCOgUob5hrTBEL3JRoZry4+BMnxnxNMWo+UXsDJAzu3phD/EgnG4MzFGsY=
