on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          make gen-docs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "docs(update): latest" || echo "No document(s) updates found!"
          git push
