name: Move PR To Needs Review

on:
  pull_request:
    types: [review_requested,ready_for_review]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: "GLab: A GitLab CLI Tool"
          column: Needs Review 👀
          repo-token: ${{ secrets.BOT_TOKEN }}
